spring:
  application:
    name: aps
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=aps;trustServerCertificate=true
    username: sa
    password: '!Sys@dmin1'
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none